config/routes.rb
Rails.application.routes.draw do

  root to: 'home#top'

  devise_for :users

  get 'home/about' => 'home#about', as:'about'
  resources :books, only: [:new, :create, :edit, :update, :index, :show, :destroy]

  resources :users, only: [:show, :index, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { maximum:200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :profile_image

  validates :name, uniqueness: true, length: { minimum: 2, maximum:20 }
  validates :introduction, length: { maximum:50 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except:[:top, :about]

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController


  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully"
      redirect_to book_path(@book.id)
    else
      @user = current_user
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render "edit"
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    @book.user_id = current_user.id
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully"
      redirect_to book_path(@book.id)
    else
      render 'edit'
    end
  end

  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

  def show
    @new_book = Book.new
    @book = Book.find(params[:id])
    @user = current_user
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books.page(params[:page]).reverse_order
  end

  def edit
    @user = User.find(params[:id])
    if @user.id == current_user.id
      render "edit"
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully"
      redirect_to user_path(@user.id)
    else
      render "edit"
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
  <h2>User info</h2>
  <table class="table">
    <tr><%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg", size: '100x100' %></tr>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
  </table>
  <div class="row">
   <%= link_to "", edit_user_path(user), class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>
  </div>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <% if @book.errors.any? %>
      <div id="error_explanation">
       <h2><%= @book.errors.count %> errors prohibited this obj from being saved:</h2>
       <ul>
        <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
       </ul>
      </div>
      <% end %>
      <%= form_with model:@book, local:true do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control book_title" %>
      </div>
      <div class="form-group">
        <%= f.label :opinion %>
        <%= f.text_area :body, class: "form-control book_body" %>
      </div>
      <div class="form-group">
        <%= f.submit "Update Book", class: "btn btn-success" %>
      </div>
      <% end %>
      <%= link_to "Show", book_path(@book.id) %>
      |
      <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= @book.errors.count %> errors prohibited this obj from being saved:</h2>
      <ul>
      <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="row">
    <div class="col-md-3">
      
      <%= render 'books/list', user: @user %>
      
      <h2 class="mt-3">New book</h2>
      <%= form_with model: @book, local:true do |f| %>
      
        <div class="form-group">
         <%= f.label :title %>
         <%= f.text_field :title, class: "form-control book_title" %>
        </div>
        
        <div class="form-group">
         <%= f.label :opinion %>
         <%= f.text_area :body, class: "form-control book_body" %>
        </div>
        
        <div class="form-group">
         <%= f.submit "Create Book", class: "btn btn-success" %>
        </div>
      <% end %>
    </div>
    
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user_id) do %>
              <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size: '40x40' %>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(book.id) do %>
              <%= book.title %>
              <% end %>
            </td>
            <td><%= book.body %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <table class="table">
       <tr><%= attachment_image_tag @book.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg", size: '100x100' %></tr>
       <tr>
        <th>name</th>
        <th><%= @book.user.name %></th>
       </tr>
       <tr>
        <th>introduction</th>
        <th><%= @book.user.introduction %></th>
       </tr>
      </table>
      <div class="row">
        <%= link_to "", edit_user_path(@book.user), class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>
      </div>
      <h2 class="mt-3">New book</h2>
      <%= form_with model: @new_book, local:true do |f| %>
      <div class="form-group">
       <%= f.label :title %>
       <%= f.text_field :title, class: "form-control book_title" %>
      </div>
      <div class="form-group">
       <%= f.label :opinion %>
       <%= f.text_area :body, class: "form-control book_body" %>
      </div>
      <div class="form-group">
       <%= f.submit "Create Book", class: "btn btn-success" %>
      </div>
     <% end %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@book.user_id) do %>
              <%= attachment_image_tag @book.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size: '40x40' %><br />
              <%= @book.user.name %>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(@book.id) do %>
              <%= @book.title %>
              <% end %>
            </td>
            <td>
              <%= @book.body %>
            </td>
            <% if @book.user == current_user %>
            <td>
              <%= link_to "Edit", edit_book_path(@book), class: "btn btn-sm btn-success" %>
            </td>
            <td>
              <%= link_to "Destroy", book_path(@book), method: :delete, "data-confirm"=>"本当に消しますか？", class: "btn btn-sm btn-danger" %>
            </td>
            <% end %>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/home/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/home/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong> !!</h1>
        <p>In <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
        <p>you can share and exchange your opinions , inpression , and emotions</p>
        <p> about various books!</p>
        <div class="btn-wrapper col-10 mx-auto">
          <div class="row"><%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %></div>
          <div class="row"><%= link_to "Sign up", new_user_registration_path, class:"btn btn-success btn-sm btn-block sign_up" %></div>
        </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1,maxium-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'%>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'%>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
            <span>Bookers</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li>
              <%= link_to " Home", user_path(current_user.id), class: 'fas fa-home nav-link text-light' %>
            </li>
            <li>
              <%= link_to " Users", users_path, class: 'fas fa-users nav-link text-light' %>
            </li>
            <li>
              <%= link_to " Books", books_path, class: 'fas fa-book-open nav-link text-light' %>
            </li>
            <li>
              <%= link_to " logout", destroy_user_session_path, method: :delete, class: 'fas fa-sign-out-alt nav-link text-light' %>
            </li>
            <% else %>
            <li>
              <%= link_to " Home", root_path, class: 'fas fa-home nav-link text-light' %>
            </li>
            <li>
              <%= link_to " About", about_path, class: 'fas fa-link nav-link text-light' %>
            </li>
            <li>
              <%= link_to " sign up", new_user_registration_path, class: 'fas fa-user-plus nav-link text-light' %>
            </li>
            <li>
              <%= link_to " login", new_user_session_path, class: 'fas fa-sign-in-alt nav-link text-light' %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
   <main>
     <p id="notice">
       <%= flash[:notice] %>
     </p>
     <%= yield %>
   </main>
   <footer>
     <div class="container mt-5">
       <div class="row">
         <div class="mx-auto">
           <p>CopyRight Infratop.inc</p>
         </div>
       </div>
     </div>
   </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
 <div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
   <h2>User info</h2>
   <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= @user.errors.count %> errors prohibited this obj from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
   <%= form_with model:@user, local:true do |f| %>
   <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control user_name" %>
   </div>
   <div class="form-group">
    <%= f.label :image %>
    <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
   </div>
   <div class="form-group">
    <%= f.label :introduction %>
    <%= f.text_area :introduction, class: "form-control user_introduction" %>
   </div>
   <div class="form-group">
    <%= f.submit "Update User", class: "btn btn-secondary" %>
   </div>
   <% end %>
   </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'books/list', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= form_with model: @book, local:true do |f| %>
      <div class="form-group">
       <%= f.label :title %>
       <%= f.text_field :title, class: "form-control book_title" %>
      </div>
      <div class="form-group">
       <%= f.label :opinion %>
       <%= f.text_area :body, class: "form-control book_body" %>
      </div>
      <div class="form-group">
       <%= f.submit "Create Book", class: "btn btn-success" %>
      </div>
      <% end %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td>
              <%= attachment_image_tag user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size: '40x40' %>
            </td>
            <td>
              <%= user.name %>
            </td>
            <td>
              <%= link_to "Show", user_path(user.id) %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
     <%= render 'books/list', user: @user %>
     <h2 class="mt-3">New book</h2>
     <%= form_with model: @book, local:true do |f| %>
     <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control book_title" %>
     </div>
     <div class="form-group">
      <%= f.label :opinion %>
      <%= f.text_area :body, class: "form-control book_body" %>
     </div>
     <div class="form-group">
      <%= f.submit "Create Book", class: "btn btn-success" %>
     </div>
     <% end %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(@user.id) do %>
              <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size: '40x40' %>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(book.id) do %>
              <%= book.title %>
              <% end %>
            </td>
            <td><%= book.body %></td>
          </tr>
          <% end %>
          <%= paginate @books %>
        </tbody>
      </table>
    </div>
  </div>
</div>